# Generated by Django 5.0.3 on 2024-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tbl_notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_date", models.DateField(auto_now_add=True)),
                ("notification_title", models.CharField(max_length=100)),
                ("notification_details", models.CharField(max_length=1000)),
                ("notification_duedate", models.DateField()),
                (
                    "notification_poster",
                    models.FileField(upload_to="Assets/PosterPhoto/"),
                ),
            ],
        ),
    ]
