# Generated by Django 5.0.3 on 2024-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
    ]
