# Generated by Django 5.0.3 on 2024-03-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0002_tbl_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_adminregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Adminregistration_name", models.CharField(max_length=50)),
                ("Adminregistration_contact", models.CharField(max_length=50)),
                ("Adminregistration_email", models.CharField(max_length=50)),
                ("Adminregistration_password", models.CharField(max_length=50)),
            ],
        ),
    ]
