# Generated by Django 5.0.3 on 2024-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0005_tbl_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designstion_name", models.CharField(max_length=50)),
            ],
        ),
    ]
