# Generated by Django 5.0.3 on 2024-03-13 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0006_tbl_designation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_designation",
            old_name="designstion_name",
            new_name="designation_name",
        ),
    ]
