# Generated by Django 5.0.3 on 2024-03-18 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0011_tbl_shopregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_shopregistration",
        ),
    ]
