# Generated by Django 5.0.3 on 2024-04-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0012_delete_tbl_shopregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_name", models.CharField(max_length=1000)),
            ],
        ),
    ]
