# Generated by Django 5.0.3 on 2024-03-18 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Guest", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_newuser",
        ),
    ]
