# Generated by Django 5.0.3 on 2024-03-20 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Guest", "0010_tbl_shopregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_shopregistration",
        ),
    ]
