# Generated by Django 5.0.3 on 2024-03-22 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Guest", "0017_tbl_professor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_newuser",
        ),
    ]
