# Generated by Django 5.0.3 on 2024-03-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Adminstrator", "0012_delete_tbl_shopregistration"),
        ("Guest", "0018_delete_tbl_newuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_gender", models.CharField(max_length=50)),
                ("user_contact", models.CharField(max_length=50)),
                ("user_email", models.CharField(max_length=50)),
                ("user_password", models.CharField(max_length=50)),
                ("user_confirmpassword", models.CharField(max_length=50)),
                ("user_address", models.CharField(max_length=50)),
                ("user_photo", models.FileField(upload_to="Assets/UserPhoto/")),
                ("user_status", models.IntegerField(default="0")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Adminstrator.tbl_place",
                    ),
                ),
            ],
        ),
    ]
