# Generated by Django 5.0.3 on 2024-04-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Guest", "0019_tbl_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateField(auto_now_add=True)),
                ("request_title", models.CharField(max_length=100)),
                ("request_details", models.CharField(max_length=1000)),
                ("request_reply", models.CharField(max_length=1000)),
                ("request_status", models.IntegerField(default="0")),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.tbl_professor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Guest.tbl_user"
                    ),
                ),
            ],
        ),
    ]
