# Generated by Django 5.0.3 on 2024-04-04 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_tbl_apply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_apply",
        ),
    ]
