# Generated by Django 5.0.3 on 2024-04-08 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0007_tbl_complaint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_apply",
        ),
    ]
