# Generated by Django 5.0.4 on 2024-04-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_tbl_user'),
        ('User', '0024_remove_tbl_predictionhead_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_predictionHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.FloatField(max_length=100)),
                ('Phosphorus', models.FloatField(max_length=100)),
                ('Potassium', models.FloatField(max_length=100)),
                ('Temprature', models.FloatField(max_length=100)),
                ('Humidity', models.FloatField(max_length=100)),
                ('Ph', models.FloatField(max_length=100)),
                ('Rainfall', models.FloatField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_predictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_result', models.CharField(max_length=100, null=True)),
                ('predictionHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_predictionhead')),
            ],
        ),
    ]
